from __future__ import annotations

from enum import Enum


class PrimaryReason(str, Enum):
    FIT = "FIT"
    SIZE_INFORMATION = "SIZE_INFORMATION"
    QUALITY = "QUALITY"
    PRODUCT_MISMATCH = "PRODUCT_MISMATCH"
    DAMAGED_OR_DEFECTIVE = "DAMAGED_OR_DEFECTIVE"
    WRONG_ITEM = "WRONG_ITEM"
    CUSTOMER_PREFERENCE = "CUSTOMER_PREFERENCE"
    DELIVERY_OR_PACKAGING = "DELIVERY_OR_PACKAGING"
    OTHER_KNOWN = "OTHER_KNOWN"
    UNCERTAIN = "UNCERTAIN"


class SubReason(str, Enum):
    TOO_SMALL = "TOO_SMALL"
    TOO_LARGE = "TOO_LARGE"
    TOO_TIGHT = "TOO_TIGHT"
    TOO_LOOSE = "TOO_LOOSE"
    TOO_SHORT = "TOO_SHORT"
    TOO_LONG = "TOO_LONG"
    FIT_OTHER = "FIT_OTHER"
    SIZE_CHART_MISMATCH = "SIZE_CHART_MISMATCH"
    SIZE_NOT_AS_EXPECTED = "SIZE_NOT_AS_EXPECTED"
    SIZE_INFORMATION_OTHER = "SIZE_INFORMATION_OTHER"
    FABRIC_QUALITY = "FABRIC_QUALITY"
    STITCHING = "STITCHING"
    FINISHING = "FINISHING"
    MATERIAL_EXPECTATION = "MATERIAL_EXPECTATION"
    QUALITY_OTHER = "QUALITY_OTHER"
    COLOUR_MISMATCH = "COLOUR_MISMATCH"
    IMAGE_MISMATCH = "IMAGE_MISMATCH"
    DESCRIPTION_MISMATCH = "DESCRIPTION_MISMATCH"
    STYLE_MISMATCH = "STYLE_MISMATCH"
    PRODUCT_MISMATCH_OTHER = "PRODUCT_MISMATCH_OTHER"
    TORN = "TORN"
    STAINED = "STAINED"
    BROKEN = "BROKEN"
    MISSING_PART = "MISSING_PART"
    MANUFACTURING_DEFECT = "MANUFACTURING_DEFECT"
    DEFECT_OTHER = "DEFECT_OTHER"
    WRONG_PRODUCT = "WRONG_PRODUCT"
    WRONG_SIZE_SENT = "WRONG_SIZE_SENT"
    WRONG_COLOUR_SENT = "WRONG_COLOUR_SENT"
    WRONG_ITEM_OTHER = "WRONG_ITEM_OTHER"
    DID_NOT_LIKE = "DID_NOT_LIKE"
    CHANGED_MIND = "CHANGED_MIND"
    STYLE_PREFERENCE = "STYLE_PREFERENCE"
    CUSTOMER_PREFERENCE_OTHER = "CUSTOMER_PREFERENCE_OTHER"
    LATE_DELIVERY = "LATE_DELIVERY"
    NOT_DELIVERED = "NOT_DELIVERED"
    PACKAGING_DAMAGED = "PACKAGING_DAMAGED"
    DELIVERY_OTHER = "DELIVERY_OTHER"


class BodyArea(str, Enum):
    CHEST = "CHEST"
    WAIST = "WAIST"
    HIP = "HIP"
    SHOULDER = "SHOULDER"
    SLEEVE = "SLEEVE"
    LENGTH = "LENGTH"
    OTHER = "OTHER"


SUB_REASONS_BY_PRIMARY: dict[PrimaryReason, set[SubReason]] = {
    PrimaryReason.FIT: {SubReason.TOO_SMALL, SubReason.TOO_LARGE, SubReason.TOO_TIGHT, SubReason.TOO_LOOSE, SubReason.TOO_SHORT, SubReason.TOO_LONG, SubReason.FIT_OTHER},
    PrimaryReason.SIZE_INFORMATION: {SubReason.SIZE_CHART_MISMATCH, SubReason.SIZE_NOT_AS_EXPECTED, SubReason.SIZE_INFORMATION_OTHER},
    PrimaryReason.QUALITY: {SubReason.FABRIC_QUALITY, SubReason.STITCHING, SubReason.FINISHING, SubReason.MATERIAL_EXPECTATION, SubReason.QUALITY_OTHER},
    PrimaryReason.PRODUCT_MISMATCH: {SubReason.COLOUR_MISMATCH, SubReason.IMAGE_MISMATCH, SubReason.DESCRIPTION_MISMATCH, SubReason.STYLE_MISMATCH, SubReason.PRODUCT_MISMATCH_OTHER},
    PrimaryReason.DAMAGED_OR_DEFECTIVE: {SubReason.TORN, SubReason.STAINED, SubReason.BROKEN, SubReason.MISSING_PART, SubReason.MANUFACTURING_DEFECT, SubReason.DEFECT_OTHER},
    PrimaryReason.WRONG_ITEM: {SubReason.WRONG_PRODUCT, SubReason.WRONG_SIZE_SENT, SubReason.WRONG_COLOUR_SENT, SubReason.WRONG_ITEM_OTHER},
    PrimaryReason.CUSTOMER_PREFERENCE: {SubReason.DID_NOT_LIKE, SubReason.CHANGED_MIND, SubReason.STYLE_PREFERENCE, SubReason.CUSTOMER_PREFERENCE_OTHER},
    PrimaryReason.DELIVERY_OR_PACKAGING: {SubReason.LATE_DELIVERY, SubReason.NOT_DELIVERED, SubReason.PACKAGING_DAMAGED, SubReason.DELIVERY_OTHER},
    PrimaryReason.OTHER_KNOWN: set(),
    PrimaryReason.UNCERTAIN: set(),
}


def allowed_sub_reasons(primary: PrimaryReason | str) -> list[str]:
    reason = PrimaryReason(primary)
    return sorted(item.value for item in SUB_REASONS_BY_PRIMARY[reason])
